[package]
name = "boj"
version = "0.1.0"
edition = "2018"

[build-dependencies]
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }

[workspace]
members = [
  "problem-1000",
  "problem-1001",
  "problem-2558",
  "problem-4828",
  "problem-10950",
]
